# Generated by Django 5.2 on 2025-05-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_alter_joke_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
