# Generated by Django 5.2 on 2025-05-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0006_alter_joke_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='tags',
            field=models.ManyToManyField(to='jokes.tag'),
        ),
    ]
