# Generated by Django 5.2 on 2025-05-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_alter_joke_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
